[package]
name = "network-programming-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.8.5"


[[example]]
name = "thread_tcp_echo_server"

[[example]]
name = "tcp_client"

[[example]]
name = "thread_udp_echo_server"

[[example]]
name = "udp_client"
